[[redirects]]
  from = "/home"
  to = "https://accounts.spotify.com/authorize?client_id=${REACT_APP_SPOTIFY_CLIENT_ID}&response_type=code&redirect_uri=https://productivitypro.netlify.app/home&scope=streaming%20user-read-email%20user-read-private%20user-library-read%20user-library-modify%20user-read-playback-state%20user-modify-playback-state%20playlist-modify%20playlist-modify-private"
  status = 200
  force = true
  headers = {X-From = "Netlify"}